### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by javiermortiz** [theflaggship/stayquaint-airbnb-clone#1]
DB Schema

- [x] Users table, email column, data type says 'sting' =D
- [x] Lodgings, has an addressId but I don't see an addresses table
- [x] Lodgings, you don't need a reviewId as that would tie a Lodging to just one review, it is the reviews that will reference the lodgings via a lodgingId FK
- [x] Lodgins, you don't need an imgUrl since all of your images urls will be in the images table
- [x] Don't forget to add your Features List to your wiki

**Comment by theflaggship** [comment]
Taken care of!
